environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"
platform:
  - x86
  - x64
install:
  - ps: Install-Product node $env:nodejs_version
  - md public
  - npm install --global --production windows-build-tools
  - npm install
build_script:
  - npm run build
test_script:
  - npm run lint
  - npm test
